grammar uk.ac.kcl.inf.mdd1.Turtles with org.eclipse.xtext.common.Terminals

generate turtles "http://www.ac.uk/kcl/inf/mdd1/Turtles"

TurtleProgram: 
       statements += Statement*
;

Statement: 
        Move | Turn
;

Move: 
        dir = Direction '(' num = INT ')'
;

enum Direction: 
        forward | backward
;

Turn: 
       'turn' d = Com 'by' num = INT 'degrees'
;

enum Com: 
       left | right
;