# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#     - name: Clean up disk space
#       run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
#     - name: Set up OpenJDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#     - name: Set up Maven
#       uses: stCarolas/setup-maven@v4.5
#       with:
#         maven-version: 3.9.5
#     - name: Checkout
#       uses: actions/checkout@v4
#     - uses: education/autograding@v1

#PREVIOUS WORKING WORKFLOW 

# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clean up disk space
#         run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY

#       - name: Set up OpenJDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - name: Set up Maven
#         uses: stCarolas/setup-maven@v4.5
#         with:
#           maven-version: 3.9.5

#       - name: Checkout
#         uses: actions/checkout@v4

#       # Step 1: Run the autograder (this will generate feedback)
#       - uses: education/autograding@v1

#       # Step 2: Make the parse script executable
#       - name: Make the parse script executable
#         run: chmod +x ./scripts/parse_and_link_feedback.sh   # This step ensures the script is executable

#       # Step 3: Run the parse and link feedback script
#       - name: Run the parse and link feedback script
#         run: ./scripts/parse_and_link_feedback.sh   # Executes the script


name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - name: Clean up disk space
      run: sudo rm -rf "/opt/ghc" "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"

    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5

    - name: Checkout repository
      uses: actions/checkout@v4

    # Run the autograder and capture output
    # - name: Run autograder
    #   id: run-autograder
    #   run: |
    #     education/autograding@v1 > autograder_output.txt 2>&1 || true
    #     cat autograder_output.txt  # Show output in logs for debugging

    - name: Run autograding
      id: autograding
      uses: education/autograding@v1

    # Display logs
    - name: Display autograding logs
      run: cat autograder_output.txt

    # Upload the autograder output as an artifact
    - name: Upload autograder output
      uses: actions/upload-artifact@v4
      with:
        name: autograder-output
        path: autograder_output.txt
