# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#     - name: Clean up disk space
#       run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
#     - name: Set up OpenJDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#     - name: Set up Maven
#       uses: stCarolas/setup-maven@v4.5
#       with:
#         maven-version: 3.9.5
#     - name: Checkout
#       uses: actions/checkout@v4
#     - uses: education/autograding@v1

# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#     - name: Clean up disk space
#       run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
#     - name: Set up OpenJDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#     - name: Set up Maven
#       uses: stCarolas/setup-maven@v4.5
#       with:
#         maven-version: 3.9.5
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Make the parse script executable
#       run: chmod +x scripts/parse_and_link_feedback.sh  # Makes your script executable
#     - uses: education/autograding@v1  # Run autograder first

#     # 🔍 Debug Step: Check if log files exist
#     - name: Debug - List Files in Target Directory
#       run: ls -R target || echo "⚠️ Target directory not found"
    

#     - name: Run the parse and link feedback script
#       run: ./scripts/parse_and_link_feedback.sh  # Executes the script
    
name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    - name: Clean up disk space
      run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    - name: Checkout
      uses: actions/checkout@v4
    - name: Make the parse script executable
      run: chmod +x scripts/parse_and_link_feedback.sh  # Makes your script executable

    # 🛠 Run the autograder first
    - uses: education/autograding@v1  # Run autograder

    # 🔍 Debug Step 1: Check all files
    - name: Debug - List All Files in Repository
      run: ls -R

    # 🔍 Debug Step 2: Check common log file locations
    - name: Debug - Check for Log Files
      run: |
        echo "Checking target directory..."
        ls -R target || echo "⚠️ Target directory not found"
        
        echo "Checking autograding logs..."
        ls -R autograding || echo "⚠️ No autograding logs found"
        
        echo "Checking default log locations..."
        find . -type f -name "*.log"

    # 🔨 Build the project (if necessary)
    - name: Build the project with Maven
      run: mvn clean package

    - name: Run Maven tests
      run: mvn test


    # 🔍 Debug Step 3: Run the script only if the log file exists
    - name: Run the parse and link feedback script
      run: |
        if [ -f target/log.txt ]; then
          ./scripts/parse_and_link_feedback.sh
        else
          echo "❌ Log file not found. Skipping script execution."
          exit 1
        fi
