# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#     - name: Clean up disk space
#       run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
#     - name: Set up OpenJDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#     - name: Set up Maven
#       uses: stCarolas/setup-maven@v4.5
#       with:
#         maven-version: 3.9.5
#     - name: Checkout
#       uses: actions/checkout@v4
#     - uses: education/autograding@v1

#PREVIOUS WORKING WORKFLOW 

# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clean up disk space
#         run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY

#       - name: Set up OpenJDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - name: Set up Maven
#         uses: stCarolas/setup-maven@v4.5
#         with:
#           maven-version: 3.9.5

#       - name: Checkout
#         uses: actions/checkout@v4

#       # Step 1: Run the autograder (this will generate feedback)
#       - uses: education/autograding@v1

#       # Step 2: Make the parse script executable
#       - name: Make the parse script executable
#         run: chmod +x ./scripts/parse_and_link_feedback.sh   # This step ensures the script is executable

#       # Step 3: Run the parse and link feedback script
#       - name: Run the parse and link feedback script
#         run: ./scripts/parse_and_link_feedback.sh   # Executes the script


name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    steps:
      - name: Clean up disk space
        run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY

      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5

      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Run the autograder (this will generate feedback)
      - name: Run Autograder
        uses: education/autograding@v1

      # Step 2: Parse the test output and save it to test_results.log
      - name: Parse Test Output and Save to Log
        run: |
          # Ensure the test results log file exists and is clean
          touch test_results.log

          # Custom command to run the autograder script if necessary (update with the correct path)
          ./path-to-autograder/autograder.sh > test_results.log 2>&1 || echo "Autograder failed" >> test_results.log

          # Optionally print out the log file to confirm the content
          cat test_results.log

      # Step 3: Upload the test results log as an artifact
      - name: Upload Test Results Log
        uses: actions/upload-artifact@v3
        with:
          name: test-results-log
          path: test_results.log
