# name: GitHub Classroom Workflow

# on: [push]

# permissions:
#   checks: write
#   actions: read
#   contents: read

# jobs:
#   build:
#     name: Autograding
#     runs-on: ubuntu-latest
#     steps:
#     - name: Clean up disk space
#       run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
#     - name: Set up OpenJDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#     - name: Set up Maven
#       uses: stCarolas/setup-maven@v4.5
#       with:
#         maven-version: 3.9.5
#     - name: Checkout
#       uses: actions/checkout@v4
#     - uses: education/autograding@v1

name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clean up disk space
      run: sudo rm -rf "/opt/ghc" && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf $AGENT_TOOLSDIRECTORY
    
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    
    - name: Checkout
      uses: actions/checkout@v4
    
    # - name: Ensure grader directory exists
    #   run: |
    #     if [ ! -d "grader" ]; then echo "❌ Grader directory does not exist"; exit 1; fi

    - name: Validate Files
      run: |
        if [ ! -f "uk.ac.kcl.inf.mdd1.turtles/model/generated/Turtles.ecore" ]; then echo "❌ Turtles.ecore file not found"; exit 1; fi
        if [ ! -f "uk.ac.kcl.inf.mdd1.turtles/model/generated/Student.ecore" ]; then echo "❌ Student.ecore file not found"; exit 1; fi

    # - name: Copy Grader JAR
    #   run: |
    #     cp grader/grader.jar ./  
    
    - name: Run Grader
      run: |
        java -jar grader/grader.jar -s uk.ac.kcl.inf.mdd1.turtles/model/generated/Turtles.ecore -a uk.ac.kcl.inf.mdd1.turtles/model/generated/Student.ecore
